

CREATE TABLE [dbo].[DM_DONVI_PHUTRACH](
	[DV_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DV_TEN] [nvarchar](50) NULL,
	[DV_STT] [int] NULL,
 CONSTRAINT [PK_DM_DONVI_PHUTRACH] PRIMARY KEY CLUSTERED 
(
	[DV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


