//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_HUYEN()
        {
            this.DM_XA = new HashSet<DM_XA>();
        }
    
        public long HUYEN_ID { get; set; }
        public string HUYEN_TEN { get; set; }
        public string HUYEN_DIENGIAI { get; set; }
        public Nullable<long> TINH_ID { get; set; }
        public Nullable<int> HUYEN_STT { get; set; }
    
        public virtual DM_TINH DM_TINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_XA> DM_XA { get; set; }
    }
}
