//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAI_HOATDONG
    {
        public long LOAIHD_ID { get; set; }
        public string LOAIHD_TEN { get; set; }
        public Nullable<int> LOAIHD_STT { get; set; }
    }
}
