//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHA_TAI_TRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_NHA_TAI_TRO()
        {
            this.DM_NHA_TAI_TRO_CHITIET = new HashSet<DM_NHA_TAI_TRO_CHITIET>();
            this.QL_HOATDONG_TAPHUAN = new HashSet<QL_HOATDONG_TAPHUAN>();
        }
    
        public long NTT_ID { get; set; }
        public string NTT_TEN { get; set; }
        public string NTT_DIACHI { get; set; }
        public string NTT_CANHAN_TOCHUC { get; set; }
        public string NTT_LOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_NHA_TAI_TRO_CHITIET> DM_NHA_TAI_TRO_CHITIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_HOATDONG_TAPHUAN> QL_HOATDONG_TAPHUAN { get; set; }
    }
}
