//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHA_TAI_TRO_CHITIET
    {
        public long NTT_CT_ID { get; set; }
        public Nullable<long> NTT_ID { get; set; }
        public string NTT_CT_HOTEN { get; set; }
        public string NTT_CT_CHUCVU { get; set; }
        public string NTT_CT_SODIENTHOAI { get; set; }
        public string NTT_CT_EMAIL { get; set; }
        public string NTT_CT_LOAI { get; set; }
    
        public virtual DM_NHA_TAI_TRO DM_NHA_TAI_TRO { get; set; }
    }
}
