//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHA_TAI_TRO_LOAI
    {
        public long LOAI_NTT_ID { get; set; }
        public string LOAI_NTT_TEN { get; set; }
        public Nullable<int> LOAI_NTT_STT { get; set; }
    }
}
