//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PHUONGTIEN_DILAI
    {
        public long PT_ID { get; set; }
        public string PT_TEN { get; set; }
        public Nullable<int> PT_STT { get; set; }
    }
}
