//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TRINH_DO_HOC_VAN
    {
        public long HV_ID { get; set; }
        public string HV_TEN { get; set; }
        public string HV_DIENGIAI { get; set; }
        public Nullable<int> HV_STT { get; set; }
    }
}
