//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TRINH_DO_CHUYEN_MON
    {
        public long CM_ID { get; set; }
        public string CM_TEN { get; set; }
        public string CM_DIENGIAI { get; set; }
        public Nullable<int> CM_STT { get; set; }
    }
}
