//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_HNXH
    {
        public long HNXH_ID { get; set; }
        public Nullable<long> HNXH_LOAI_ID { get; set; }
        public string HNXH_TEN { get; set; }
        public Nullable<System.DateTime> HNXH_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> HNXH_THOIGIAN_KETTHUC { get; set; }
        public Nullable<int> HNXH_TONGSO_NGAY { get; set; }
        public string HNXH_DIADIEM { get; set; }
        public Nullable<int> HNXH_SOLUONG { get; set; }
        public string HNXH_DOITUONG_TEN { get; set; }
        public string HNXH_DOITUONG_ID { get; set; }
        public string HNXH_DOITUONG_KHAC { get; set; }
        public Nullable<int> HNXH_TONGSO_TIEN { get; set; }
        public string HNXH_DONVI_THUCHIEN { get; set; }
        public string HNXH_NOIDUNG { get; set; }
    }
}
