//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_GIAIQUYET_VIECLAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QL_HOATDONG_GIAIQUYET_VIECLAM()
        {
            this.QL_HOATDONG_GIAIQUYET_VIECLAM_CHITIET = new HashSet<QL_HOATDONG_GIAIQUYET_VIECLAM_CHITIET>();
        }
    
        public long GQVL_ID { get; set; }
        public string GQVL_TEN { get; set; }
        public Nullable<System.DateTime> GQVL_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> GQVL_THOIGIAN_KETTHUC { get; set; }
        public string GQVL_DIADIEM { get; set; }
        public Nullable<int> GQVL_THAMGIA_SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_HOATDONG_GIAIQUYET_VIECLAM_CHITIET> QL_HOATDONG_GIAIQUYET_VIECLAM_CHITIET { get; set; }
        public virtual QL_HOATDONG_GIAIQUYET_VIECLAM QL_HOATDONG_GIAIQUYET_VIECLAM1 { get; set; }
        public virtual QL_HOATDONG_GIAIQUYET_VIECLAM QL_HOATDONG_GIAIQUYET_VIECLAM2 { get; set; }
    }
}
