//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_VIECLAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QL_HOATDONG_VIECLAM()
        {
            this.QL_HOATDONG_VIECLAM_DOITUONG_KHAC = new HashSet<QL_HOATDONG_VIECLAM_DOITUONG_KHAC>();
        }
    
        public long VL_ID { get; set; }
        public Nullable<long> VL_LOAI_ID { get; set; }
        public string VL_TEN { get; set; }
        public Nullable<System.DateTime> VL_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> VL_THOIGIAN_KETTHUC { get; set; }
        public Nullable<int> VL_TONGSO_NGAY { get; set; }
        public string VL_DIADIEM { get; set; }
        public string VL_DONVI_GIOITHIEU { get; set; }
        public Nullable<int> VL_SOLUONG { get; set; }
        public Nullable<int> VL_SOLUONG_NU { get; set; }
        public Nullable<int> VL_THUNHAP_THANG { get; set; }
        public string VL_DOITUONG_TEN { get; set; }
        public string VL_DOITUONG_ID { get; set; }
        public string VL_DOITUONG_KHAC { get; set; }
        public string VL_NOIDUNG { get; set; }
    
        public virtual QL_HOATDONG_VIECLAM QL_HOATDONG_VIECLAM1 { get; set; }
        public virtual QL_HOATDONG_VIECLAM QL_HOATDONG_VIECLAM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_HOATDONG_VIECLAM_DOITUONG_KHAC> QL_HOATDONG_VIECLAM_DOITUONG_KHAC { get; set; }
    }
}
