//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOIVIEN_CON
    {
        public long CON_ID { get; set; }
        public Nullable<long> HV_ID { get; set; }
        public string CON_TEN { get; set; }
        public string CON_GIOITINH { get; set; }
        public Nullable<System.DateTime> CON_NGAYSINH { get; set; }
        public string CON_GHICHU { get; set; }
    
        public virtual QL_HOIVIEN QL_HOIVIEN { get; set; }
    }
}
