//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_HOICHO_TRIENLAM
    {
        public long HC_ID { get; set; }
        public string HC_TEN { get; set; }
        public Nullable<System.DateTime> HC_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> HC_THOIGIAN_KETTHUC { get; set; }
        public Nullable<int> HC_TONGSO_NGAY { get; set; }
        public string HC_DIADIEM { get; set; }
        public Nullable<int> HC_SOLUONG { get; set; }
        public Nullable<int> HC_SOLUONG_NU { get; set; }
        public string HC_TAITRO_DONVI { get; set; }
        public Nullable<int> HC_TAITRO_SOTEN { get; set; }
        public Nullable<int> HC_SOTIEN_SAU_BANHANG { get; set; }
        public string HC_DOITUONG_TEN { get; set; }
        public string HC_DOITUONG_ID { get; set; }
        public string HC_DOITUONG_KHAC { get; set; }
        public string HC_NOIDUNG { get; set; }
    }
}
