//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_HNXH_DOITUONG_KHAC
    {
        public long DTK_ID { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public string DTK_HO { get; set; }
        public string DTK_TEN { get; set; }
        public string DTK_GIOITINH { get; set; }
        public string DTK_CHUCVU { get; set; }
        public string DTK_DIACHI { get; set; }
        public string DTK_SDT { get; set; }
        public string DTK_MASOTHUE { get; set; }
        public string DTK_EMAIL { get; set; }
        public string DTK_FACEBOOK { get; set; }
        public string DTK_CMND_SO { get; set; }
        public Nullable<System.DateTime> DTK_CMND_NGAYCAP { get; set; }
        public string DTK_CMND_NOICAP { get; set; }
        public string DTK_DONVI_TEN { get; set; }
        public string DTK_DONVI_DIACHI { get; set; }
        public string DTK_DONVI_SDT { get; set; }
        public string DTK_TK_SO { get; set; }
        public string DTK_TK_NGANHANG { get; set; }
        public string DTK_TK_DIACHI { get; set; }
    
        public virtual QL_HOATDONG_HNXH QL_HOATDONG_HNXH { get; set; }
    }
}
