//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_VIECLAM
    {
        public long VL_ID { get; set; }
        public Nullable<int> VL_LOAI_ID { get; set; }
        public string VL_TEN { get; set; }
        public Nullable<System.DateTime> VL_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> VL_THOIGIAN_KETTHUC { get; set; }
        public string VL_DIADIEM { get; set; }
        public string VL_DONVI_GIOITHIEU { get; set; }
        public Nullable<int> VL_SOLUONG { get; set; }
        public Nullable<int> VL_SOLUONG_NU { get; set; }
        public Nullable<int> VL_THUNHAP_THANG { get; set; }
        public string VL_DOITUONG { get; set; }
        public string VL_NOIDUNG { get; set; }
    
        public virtual QL_HOATDONG_VIECLAM QL_HOATDONG_VIECLAM1 { get; set; }
        public virtual QL_HOATDONG_VIECLAM QL_HOATDONG_VIECLAM2 { get; set; }
    }
}
