//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_DAYNGHE
    {
        public long DN_ID { get; set; }
        public string DN_TEN { get; set; }
        public Nullable<System.DateTime> DN_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> DN_THOIGIAN_KETTHUC { get; set; }
        public string DN_DIADIEM { get; set; }
        public string DN_NGHE { get; set; }
        public string DN_DONVI_THUCHIEN { get; set; }
        public Nullable<int> DN_SOLUONG { get; set; }
        public Nullable<int> DN_SOLUONG_NU { get; set; }
        public Nullable<int> DN_TONGTIEN { get; set; }
        public string DN_DOITUONG_THAMGIA { get; set; }
        public string DN_NOIDUNG { get; set; }
        public string DN_NGUOI_HOTRO { get; set; }
    }
}
