//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_VAYVON
    {
        public long VV_ID { get; set; }
        public string VV_TEN { get; set; }
        public Nullable<System.DateTime> VV_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> VV_THOIGIAN_KETTHUC { get; set; }
        public Nullable<int> VV_TONGSO_NGAY { get; set; }
        public string VV_DIADIEM { get; set; }
        public Nullable<int> VV_SOLUONG { get; set; }
        public Nullable<int> VV_SOLUONG_NU { get; set; }
        public string VV_NGUON_VAY { get; set; }
        public Nullable<int> VV_TIEN_VAY { get; set; }
        public Nullable<System.DateTime> VV_THOIGIAN_TRA { get; set; }
        public string VV_PHUONGTHUC_TRA { get; set; }
        public string VV_DOITUONG { get; set; }
        public string VV_NOIDUNG { get; set; }
    }
}
