//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_DAYNGHE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QL_HOATDONG_DAYNGHE()
        {
            this.QL_HOATDONG_DAYNGHE_DOITUONG_KHAC = new HashSet<QL_HOATDONG_DAYNGHE_DOITUONG_KHAC>();
        }
    
        public long DN_ID { get; set; }
        public string DN_TEN { get; set; }
        public Nullable<System.DateTime> DN_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> DN_THOIGIAN_KETTHUC { get; set; }
        public Nullable<int> DN_TONGSO_NGAY { get; set; }
        public string DN_DIADIEM { get; set; }
        public string DN_NGHE { get; set; }
        public string DN_DONVI_THUCHIEN { get; set; }
        public Nullable<int> DN_SOLUONG { get; set; }
        public Nullable<int> DN_SOLUONG_NU { get; set; }
        public Nullable<int> DN_TONGTIEN { get; set; }
        public string DN_DOITUONG_THAMGIA { get; set; }
        public string DN_DOITUONG_THAMGIA_ID { get; set; }
        public string DN_NOIDUNG { get; set; }
        public string DN_NGUOI_HOTRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_HOATDONG_DAYNGHE_DOITUONG_KHAC> QL_HOATDONG_DAYNGHE_DOITUONG_KHAC { get; set; }
    }
}
