//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_TAPHUAN
    {
        public long TH_ID { get; set; }
        public string TH_TEN { get; set; }
        public Nullable<System.DateTime> TH_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> TH_THOIGIAN_KETTHUC { get; set; }
        public string TH_DIADIEM { get; set; }
        public Nullable<int> TH_THAMGIA_SOLUONG { get; set; }
        public Nullable<int> TH_SOTIEN_HOTRO { get; set; }
        public string TH_GIANGVIEN_HOTEN { get; set; }
        public string TH_GIANGVIEN_DIACHI { get; set; }
        public string TH_GIANGVIEN_DIENTHOAI { get; set; }
        public Nullable<int> TH_GIANGVIEN_THULAO { get; set; }
        public string TH_GIANGVIEN_CHIPHI_KHAC { get; set; }
        public string TH_GIANGVIEN_HOTEN2 { get; set; }
        public string TH_GIANGVIEN_DIACHI2 { get; set; }
        public string TH_GIANGVIEN_DIENTHOAI2 { get; set; }
        public Nullable<int> TH_GIANGVIEN_THULAO2 { get; set; }
        public string TH_GIANGVIEN_CHIPHI_KHAC2 { get; set; }
        public string TH_HOTRO_HOTEN { get; set; }
        public string TH_HOTRO_DIACHI { get; set; }
        public string TH_HOTRO_DIENTHOAI { get; set; }
        public Nullable<int> TH_HOTRO_THULAO { get; set; }
    }
}
