//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_VAYVON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QL_HOATDONG_VAYVON()
        {
            this.QL_HOATDONG_VAYVON_CHITIET = new HashSet<QL_HOATDONG_VAYVON_CHITIET>();
        }
    
        public long VV_ID { get; set; }
        public string VV_TEN { get; set; }
        public Nullable<System.DateTime> VV_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> VV_THOIGIAN_KETTHUC { get; set; }
        public string VV_DIADIEM { get; set; }
        public Nullable<int> VV_THAMGIA_SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_HOATDONG_VAYVON_CHITIET> QL_HOATDONG_VAYVON_CHITIET { get; set; }
    }
}
