//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_VAYVON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QL_HOATDONG_VAYVON()
        {
            this.QL_HOATDONG_VAYVON_DOITUONG_KHAC = new HashSet<QL_HOATDONG_VAYVON_DOITUONG_KHAC>();
        }
    
        public long VV_ID { get; set; }
        public string VV_TEN { get; set; }
        public Nullable<System.DateTime> VV_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> VV_THOIGIAN_KETTHUC { get; set; }
        public Nullable<int> VV_TONGSO_NGAY { get; set; }
        public string VV_DIADIEM { get; set; }
        public Nullable<int> VV_SOLUONG { get; set; }
        public Nullable<int> VV_SOLUONG_NU { get; set; }
        public string VV_NGUON_VAY { get; set; }
        public Nullable<int> VV_TIEN_VAY { get; set; }
        public Nullable<System.DateTime> VV_THOIGIAN_TRA { get; set; }
        public string VV_PHUONGTHUC_TRA { get; set; }
        public string VV_DOITUONG_TEN { get; set; }
        public string VV_DOITUONG_ID { get; set; }
        public string VV_DOITUONG_KHAC { get; set; }
        public string VV_NOIDUNG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_HOATDONG_VAYVON_DOITUONG_KHAC> QL_HOATDONG_VAYVON_DOITUONG_KHAC { get; set; }
    }
}
