//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_ASXH
    {
        public long ASXH_ID { get; set; }
        public Nullable<long> ASXH_LOAI_ID { get; set; }
        public string ASXH_TEN { get; set; }
        public Nullable<System.DateTime> ASXH_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> ASXH_THOIGIAN_KETTHUC { get; set; }
        public Nullable<int> ASXH_TONGSO_NGAY { get; set; }
        public string ASXH_DIADIEM { get; set; }
        public Nullable<int> ASXH_SOLUONG { get; set; }
        public Nullable<int> ASXH_TONGSO_TIEN { get; set; }
        public string ASXH_DOITUONG_TEN { get; set; }
        public string ASXH_DOITUONG_ID { get; set; }
        public string ASXH_DOITUONG_KHAC { get; set; }
        public string ASXH_DONVI_THUCHIEN { get; set; }
        public string ASXH_NOIDUNG { get; set; }
    }
}
