//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOIVIEN_IMAGE
    {
        public long IMG_ID { get; set; }
        public Nullable<long> HV_ID { get; set; }
        public byte[] IMG_HOIVIEN { get; set; }
        public byte[] IMG_CMND_MATTRUOC { get; set; }
        public byte[] IMG_CMND_MATSAU { get; set; }
    
        public virtual QL_HOIVIEN QL_HOIVIEN { get; set; }
    }
}
