//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_GIAIQUYET_VIECLAM_CHITIET
    {
        public long GQVL_CT_ID { get; set; }
        public Nullable<long> GQVL_ID { get; set; }
        public Nullable<long> HV_ID { get; set; }
        public Nullable<int> GQVL_CT_THU_NHAP { get; set; }
    
        public virtual QL_HOATDONG_GIAIQUYET_VIECLAM QL_HOATDONG_GIAIQUYET_VIECLAM { get; set; }
        public virtual QL_HOIVIEN QL_HOIVIEN { get; set; }
    }
}
