//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_NHATAITRO
    {
        public long NTT_ID { get; set; }
        public Nullable<long> ASXH_ID { get; set; }
        public Nullable<long> HNXH_ID { get; set; }
        public Nullable<long> KHAC_ID { get; set; }
        public string NTT_TEN { get; set; }
        public string NTT_DIACHI { get; set; }
        public string NTT_CANHAN_TOCHUC { get; set; }
        public Nullable<int> NTT_SOTIEN { get; set; }
        public string NTT_GHICHU { get; set; }
        public string NTT_LOAI { get; set; }
        public string NTT_NDD_HOTEN { get; set; }
        public string NTT_NDD_CHUCVU { get; set; }
        public string NTT_NDD_SDT { get; set; }
        public string NTT_NDD_EMAIL { get; set; }
    
        public virtual QL_HOATDONG_ASXH QL_HOATDONG_ASXH { get; set; }
        public virtual QL_HOATDONG_HNXH QL_HOATDONG_HNXH { get; set; }
        public virtual QL_HOATDONG_KHAC QL_HOATDONG_KHAC { get; set; }
    }
}
