//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_DAYNGHE
    {
        public long DN_ID { get; set; }
        public string DN_TEN { get; set; }
        public Nullable<System.DateTime> DN_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> DN_THOIGIAN_KETTHUC { get; set; }
        public string DN_DIADIEM { get; set; }
        public Nullable<int> DN_THAMGIA_SOLUONG { get; set; }
        public Nullable<int> DN_SOTIEN_HOTRO { get; set; }
        public string DN_HOTRO_HOTEN { get; set; }
        public string DN_HOTRO_DIACHI { get; set; }
        public string DN_HOTRO_DIENTHOAI { get; set; }
        public Nullable<int> DN_HOTRO_THULAO { get; set; }
    }
}
