//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOATDONG_HOITHAO
    {
        public long HT_ID { get; set; }
        public Nullable<long> HT_LOAI_ID { get; set; }
        public string HT_TEN { get; set; }
        public Nullable<System.DateTime> HT_THOIGIAN_BATDAU { get; set; }
        public Nullable<System.DateTime> HT_THOIGIAN_KETTHUC { get; set; }
        public Nullable<int> HT_TONGSO_NGAY { get; set; }
        public string HT_DIADIEM { get; set; }
        public string HT_NOIDUNG { get; set; }
        public string HT_DONVI_THUCHIEN { get; set; }
        public Nullable<int> HT_SOLUONG { get; set; }
        public Nullable<int> HT_SOTIEN_HOTRO { get; set; }
        public string HT_NGUOI_HOTRO { get; set; }
        public Nullable<int> HT_NGUOI_HOTRO_THULAO { get; set; }
    }
}
