//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOIVIEN
    {
        public long HV_ID { get; set; }
        public string HV_TEN { get; set; }
        public string HV_GIOI_TINH { get; set; }
        public string HV_DAN_TOC { get; set; }
        public Nullable<System.DateTime> HV_NGAY_SINH { get; set; }
        public Nullable<long> HV_TON_GIAO_ID { get; set; }
        public Nullable<long> HV_NGHE_NGHIEP_ID { get; set; }
        public Nullable<long> HV_TRINHDO_VANHOA_ID { get; set; }
        public Nullable<long> HV_TRINHDO_CHUYENMON_ID { get; set; }
        public string HV_CMND { get; set; }
        public Nullable<System.DateTime> HV_CMND_NGAY { get; set; }
        public string HV_CMND_NOICAP { get; set; }
        public Nullable<System.DateTime> HV_KHUYETTAT_NGAY { get; set; }
        public string HV_CHUCVU { get; set; }
        public string HV_THUONGTRU_DUONG { get; set; }
        public string HV_THUONGTRU_KHUVUC { get; set; }
        public Nullable<long> HV_THUONGTRU_PHUONG { get; set; }
        public Nullable<long> HV_THUONGTRU_QUAN { get; set; }
        public Nullable<long> HV_THUONGTRU_TP { get; set; }
        public string HV_TAMTRU_DUONG { get; set; }
        public string HV_TAMTRU_KHUVUC { get; set; }
        public Nullable<long> HV_TAMTRU_PHUONG { get; set; }
        public Nullable<long> HV_TAMTRU_QUAN { get; set; }
        public Nullable<long> HV_TAMTRU_TP { get; set; }
    }
}
