//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_HOIVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QL_HOIVIEN()
        {
            this.QL_HOIVIEN_CON = new HashSet<QL_HOIVIEN_CON>();
            this.QL_HOIVIEN_HOIPHI = new HashSet<QL_HOIVIEN_HOIPHI>();
        }
    
        public long HV_ID { get; set; }
        public string HV_HO { get; set; }
        public string HV_TEN { get; set; }
        public byte[] HV_IMAGE { get; set; }
        public string HV_GIOI_TINH { get; set; }
        public string HV_DAN_TOC { get; set; }
        public Nullable<System.DateTime> HV_NGAY_SINH { get; set; }
        public Nullable<int> HV_TUOI { get; set; }
        public string HV_TON_GIAO { get; set; }
        public string HV_NGHE_NGHIEP { get; set; }
        public string HV_TRINHDO_VANHOA { get; set; }
        public string HV_TRINHDO_CHUYENMON { get; set; }
        public string HV_NGOAINGU { get; set; }
        public string HV_CMND { get; set; }
        public Nullable<System.DateTime> HV_CMND_NGAY { get; set; }
        public string HV_CMND_NOICAP { get; set; }
        public Nullable<int> HV_KHUYETTAT_NAM { get; set; }
        public string HV_CHUCVU { get; set; }
        public string HV_THUONGTRU_KHUVUC { get; set; }
        public string HV_THUONGTRU_DUONG { get; set; }
        public string HV_THUONGTRU_PHUONG { get; set; }
        public string HV_THUONGTRU_QUAN { get; set; }
        public string HV_THUONGTRU_TP { get; set; }
        public string HV_THUONGTRU_DIACHI { get; set; }
        public string HV_TAMTRU_KHUVUC { get; set; }
        public string HV_TAMTRU_DUONG { get; set; }
        public string HV_TAMTRU_PHUONG { get; set; }
        public string HV_TAMTRU_QUAN { get; set; }
        public string HV_TAMTRU_TP { get; set; }
        public string HV_TAMTRU_DIACHI { get; set; }
        public string HV_DIENTHOAI { get; set; }
        public string HV_EMAIL { get; set; }
        public string HV_COQUAN { get; set; }
        public string HV_COQUAN_DIACHI { get; set; }
        public string HV_KT_TINHTRANG { get; set; }
        public string HV_KT_TINHTRANG_CHITIET { get; set; }
        public string HV_KT_KHAC { get; set; }
        public string HV_KT_MUCDO { get; set; }
        public string HV_PHUONGTIEN_DILAI { get; set; }
        public string HV_TINHTRANG_SUCKHOE { get; set; }
        public string HV_KT_NGUYENNHAN { get; set; }
        public string HV_KT_NGUYENNHAN_CHITIET { get; set; }
        public string HV_TINHTRANG_HONNHAN { get; set; }
        public string HV_VOCHONG { get; set; }
        public Nullable<int> HV_SOCON { get; set; }
        public string HV_CON1_TEN { get; set; }
        public Nullable<System.DateTime> HV_CON1_NGAYSINH { get; set; }
        public string HV_CON1_GIOITINH { get; set; }
        public string HV_CON1_HOCTRUONG { get; set; }
        public string HV_CON2_TEN { get; set; }
        public Nullable<System.DateTime> HV_CON2_NGAYSINH { get; set; }
        public string HV_CON2_GIOITINH { get; set; }
        public string HV_CON2_HOCTRUONG { get; set; }
        public string HV_PHONGTRAO_THETHAO { get; set; }
        public string HV_PHONGTRAO_MONGMUON { get; set; }
        public string HV_NGUYENVONG { get; set; }
        public string HV_DUNGCU_HOTRO { get; set; }
        public Nullable<System.DateTime> HV_DCHT_THOIDIEM_NHAN { get; set; }
        public string HV_DCHT_TU_TOCHUC { get; set; }
        public string HV_DCHT_TINHTRANG { get; set; }
        public Nullable<bool> HV_BTXH_NHAN_HANGTHANG { get; set; }
        public Nullable<int> HV_BTXH_TIEN_HANGTHANG { get; set; }
        public string HV_BTXH_KHAC { get; set; }
        public Nullable<bool> HV_BHYT_MIENPHI { get; set; }
        public Nullable<bool> HV_QUYETDINH_CONGNHAN_KT { get; set; }
        public Nullable<bool> HV_GIAY_CHUNGNHAN_KT { get; set; }
        public string HV_THE_KHUYETTAT { get; set; }
        public Nullable<bool> HV_GIADINH_CHINHSACH { get; set; }
        public string HV_NOI_SINH_SONG { get; set; }
        public string HV_DIEUKIEN_SONG_KHAC { get; set; }
        public string HV_NHA { get; set; }
        public string HV_SONG_VOI { get; set; }
        public string HV_SONG_VOI_CHITIET { get; set; }
        public string HV_CHAMSOC_BANTHAN { get; set; }
        public string HV_HOTRO_BOI_NGUOIKHAC { get; set; }
        public string HV_VIECLAM { get; set; }
        public Nullable<int> HV_VIECLAM_THUNHAP { get; set; }
        public Nullable<bool> HV_TRE_DIHOC { get; set; }
        public string HV_NHUCAU { get; set; }
        public string HV_THANHVIEN_HOI { get; set; }
        public string HV_GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_HOIVIEN_CON> QL_HOIVIEN_CON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_HOIVIEN_HOIPHI> QL_HOIVIEN_HOIPHI { get; set; }
    }
}
