//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_NHATKY
    {
        public long NK_ID { get; set; }
        public string NK_BANG { get; set; }
        public string NK_THAOTAC { get; set; }
        public string NK_USERNAME { get; set; }
        public Nullable<System.DateTime> NK_NGAY { get; set; }
        public string NK_GIATRI_CU { get; set; }
        public string NK_GIATRI_MOI { get; set; }
    }
}
