//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_USERS_PERMISSION
    {
        public long PER_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<int> PER_NAME { get; set; }
        public Nullable<bool> PER_VIEW { get; set; }
        public Nullable<bool> PER_ADD { get; set; }
        public Nullable<bool> PER_MODIFY { get; set; }
        public Nullable<bool> PER_DELETE { get; set; }
        public Nullable<bool> PER_PRINT { get; set; }
    
        public virtual QL_USERS QL_USERS { get; set; }
    }
}
