//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauThau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QL_USERS()
        {
            this.QL_USERS_PERMISSION = new HashSet<QL_USERS_PERMISSION>();
        }
    
        public long USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_FULLNAME { get; set; }
        public string USER_PASS { get; set; }
        public Nullable<bool> USER_LOCK { get; set; }
        public Nullable<bool> USER_ADMIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_USERS_PERMISSION> QL_USERS_PERMISSION { get; set; }
    }
}
