

CREATE TABLE [dbo].[DM_NHA_TAI_TRO_CHITIET](
	[NTT_CT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NTT_CT_HOTEN] [nvarchar](50) NULL,
	[NTT_CT_CHUCVU] [nvarchar](50) NULL,
	[NTT_CT_SODIENTHOAI] [nvarchar](50) NULL,
	[NTT_CT_EMAIL] [nvarchar](50) NULL,
	[NTT_ID] [bigint] NULL,
 CONSTRAINT [PK_DM_NHA_TAI_TRO_CHITIET] PRIMARY KEY CLUSTERED 
(
	[NTT_CT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[DM_NHA_TAI_TRO_CHITIET]  WITH CHECK ADD  CONSTRAINT [FK_DM_NHA_TAI_TRO_CHITIET_DM_NHA_TAI_TRO] FOREIGN KEY([NTT_ID])
REFERENCES [dbo].[DM_NHA_TAI_TRO] ([NTT_ID])
GO

ALTER TABLE [dbo].[DM_NHA_TAI_TRO_CHITIET] CHECK CONSTRAINT [FK_DM_NHA_TAI_TRO_CHITIET_DM_NHA_TAI_TRO]
GO


