

CREATE TABLE [dbo].[DM_LOAI_HOATDONG](
	[LOAIHD_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOAIHD_TEN] [nvarchar](50) NULL,
	[LOAIHD_STT] [int] NULL,
 CONSTRAINT [PK_DM_LOAI_HOATDONG] PRIMARY KEY CLUSTERED 
(
	[LOAIHD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


