

CREATE TABLE [dbo].[DM_NHA_TAI_TRO_LOAI](
	[LOAI_NTT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOAI_NTT_TEN] [nvarchar](50) NULL,
	[LOAI_NTT_STT] [int] NULL,
 CONSTRAINT [PK_DM_NHA_TAI_TRO_LOAI] PRIMARY KEY CLUSTERED 
(
	[LOAI_NTT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


