

CREATE TABLE [dbo].[QL_HOATDONG_TAPHUAN_DIADIEM](
	[TH_DD_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TH_ID] [bigint] NULL,
	[TH_DD_TEN] [nvarchar](50) NULL,
	[TH_DD_DIACHI] [nvarchar](250) NULL,
	[TH_DD_MST] [nvarchar](50) NULL,
	[TH_DD_SDT] [nvarchar](50) NULL,
	[TH_DD_TK_SO] [nvarchar](50) NULL,
	[TH_DD_TK_TEN] [nvarchar](50) NULL,
	[TH_DD_TK_NGANHANG] [nvarchar](50) NULL,
	[TH_DD_LINK_HOPDONG] [nvarchar](250) NULL,
 CONSTRAINT [PK_QL_HOATDONG_TAPHUAN_DIADIEM] PRIMARY KEY CLUSTERED 
(
	[TH_DD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[QL_HOATDONG_TAPHUAN_DIADIEM]  WITH CHECK ADD  CONSTRAINT [FK_QL_HOATDONG_TAPHUAN_DIADIEM_QL_HOATDONG_TAPHUAN] FOREIGN KEY([TH_ID])
REFERENCES [dbo].[QL_HOATDONG_TAPHUAN] ([TH_ID])
GO

ALTER TABLE [dbo].[QL_HOATDONG_TAPHUAN_DIADIEM] CHECK CONSTRAINT [FK_QL_HOATDONG_TAPHUAN_DIADIEM_QL_HOATDONG_TAPHUAN]
GO


