USE [QL_HOIVIEN_KT]
GO

/****** Object:  Table [dbo].[QL_HOIVIEN_THANHVIENHOI]    Script Date: 06/06/2019 15:30:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QL_HOIVIEN_THANHVIENHOI](
	[TV_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HV_ID] [bigint] NULL,
	[TVH_TEN] [nvarchar](250) NULL,
	[TV_NGAY] [date] NULL,
	[TV_GHICHU] [nvarchar](150) NULL,
 CONSTRAINT [PK_QL_HOIVIEN_THANHVIENHOI] PRIMARY KEY CLUSTERED 
(
	[TV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[QL_HOIVIEN_THANHVIENHOI]  WITH CHECK ADD  CONSTRAINT [FK_QL_HOIVIEN_THANHVIENHOI_QL_HOIVIEN] FOREIGN KEY([HV_ID])
REFERENCES [dbo].[QL_HOIVIEN] ([HV_ID])
GO

ALTER TABLE [dbo].[QL_HOIVIEN_THANHVIENHOI] CHECK CONSTRAINT [FK_QL_HOIVIEN_THANHVIENHOI_QL_HOIVIEN]
GO


